### ISSUE TITLE
Records duplicate with every push

### ISSUE THREAD

**Issue by sabgaby** [algolia/jekyll-algolia#39]
## I want to report a bug:

**What is the current behavior?**
1. Every time I push to algolia, it just duplicates all the records.
2. Also, not all the settings are copied , or updated to the index
For example:
```yml
algolia:
  settings:
    attributesToSnippet: ['content:10']
```
rendered:
![screen shot 2018-02-02 at 20 41 51](https://user-images.githubusercontent.com/5911330/35751653-9bf8a98a-0859-11e8-924e-5de164576b46.png)

**What is your expected behavior?**
1. I would expect it compares the records and only make the changes accordingly. Every time I get this:
```
Found 116 files                                                                  
Updating settings                                                                
Inspecting existing records in index diybiosphere...                             
Updating records in index diybiosphere...                                        
Records to delete: 0                                                             
Records to add:    247                                                           
✔ Indexing complete 
```
2. I would expect all my settings to pass to the index. But even when I try to set up `['*']` in `attributesToRetrieve` or something. It doesn't render appropriately

**Steps to reproduce the issue:**
This is my repo: https://github.com/DIYbiosphere/sphere

**Comment by pixelastic** [comment]
Thank a lot for the issues.

Your settings for `attributesToSnippet` seem ok, there might something wrong in the way it's parsed. I'm going to check that.

As for the duplicated records, I'll have to try on your repository to see what is going on. Thank you for providing the link, it will make my job easier.

**Comment by nfrankel** [comment]
Coming back from [issue 38](https://github.com/algolia/jekyll-algolia/issues/38).

My index is limited to 10k. I have 8k entries. Every time I make a change and need to update the index, I have to clear the index before, or be blocked because the index is over 10k.
In turn, this increases my number of operations, and now I'm over quota.
Would you mind increasing the priority of this one, as it now disable search (since the quota has been reached)?

**Comment by pixelastic** [comment]
@sabgaby I think I found out why you had duplicated records. It seems that on every build you are randomly changing the `uberimage` attribute of your posts ([see here](https://github.com/DIYbiosphere/sphere/blob/master/_plugins/jekyll-sibling-images.rb#L99)).

From the plugin POV it means it's a completely different record, so it tries to reindex it. 

A solution would be to remove this field from the indexing using a [custom hook](https://community.algolia.com/jekyll-algolia/hooks.html#before-indexing-each), like this:

```rb
module Jekyll
  module Algolia
    module Hooks
      def self.before_indexing_each(record)
        record.delete(:uberimage)

        record
      end
    end
  end
end
```

Could you let me know if it solved your problem?

I found a few other issues related to double pushing of elements that I'll be releasing soon, but this might already fix your issue.

**Comment by pixelastic** [comment]
@nfrankel and @sabgaby I just released v1.1.3 that should fix the "double posting" issue. 

What was happening is that you were both using a plugin that was adding hidden objects to the records (from `jekyll-asciidoc` and `jekyll-last-modified-at`). Those objects were then serialized into the records, but because their serialized version contained a unique random ID, it was considered as a new record each time.

I added a more thorough conversion of the records, keeping simple values (numbers, booleans, strings), but attempting to convert to string all other values, and excluding anything that looks like a serialized object. I tested on both your websites and it works \o/

@sabgaby you might still need to exclude the random `uberimage` from your records using the hook I posted above. I've also moved the other issue about snippeting in its own issue (#49)

_I'll close the issue for now, but will re-open it if you tell me it's still broken_

**Comment by nfrankel** [comment]
I'm sorry, I'm using the latest 1.1.3 release and I still have the same issue...

```
Configuration file: /Users/i303869/projects/private/nfrankel.gitlab.io/_config.yml
Processing site...                                                               
Extracting records...                                                            
Updating records in index blog.frankel.ch...                                     
Records to delete: 8965                                                          
Records to add:    8965                                                          
[jekyll-algolia] Error:                                                          
403: Cannot POST to https://0A7WW73SHL.algolia.net/1/indexes/*/batch: {"message":"Record quota exceeded, change plan or delete records.","status":403} (403)
```

When you tested on my site, which account were you using? I'm afraid you might have used a super-user like last time.

**Comment by pixelastic** [comment]
Erf. Ok, I'm going to create a brand new account and see what is going on.

**Comment by nfrankel** [comment]
I tested on the `master` branch. The `feature/search` branch has been merged some time ago.

**Comment by pixelastic** [comment]
(@nfrankel and I have been solving the issue through email)

If this happens to you also, try clearing the index if it's full of "double-posted" records or upgrade to v1.1.4, that should fix it.

**Comment by nfrankel** [comment]
I confirm that it works in my case. This is my first push with a new post and the diff seems good:
<img width="788" alt="screen shot 2018-03-05 at 00 29 26" src="https://user-images.githubusercontent.com/752258/36952158-5e9cbd86-200c-11e8-893b-20aa8e449234.png">

**Comment by sabgaby** [comment]
@pixelastic, sorry to come late to this reply.
- I updated jekyll algolia
- added the hook
- did a `dry-run`
=> Still got:
```
Updating records in index diybiosphere...                                        
Records to delete: 0                                                             
Records to add:    260 
```

I also tried removing the creation of an `uberimage` alltogether and used a hack with mustache to loop through possible images in my instantsearch page
=> still get
```
Updating records in index diybiosphere...                                        
Records to delete: 0                                                             
Records to add:    260 
```

**Comment by pixelastic** [comment]
@sabgaby No need to apologize, I thank **you** for taking the time to dig further and provide more information, it made my debugging job easier.

I just published v1.2 and tried your website (on the `master` branch) with it, and I could not reproduce the issue. Could you give it a try? (running `bundle update jekyll-algolia` should do it). Version 1.2 has had a major rewrite, so it might have fixed your issue.

Otherwise, could you let me know the steps so I can replicate the issue on my side?

**Comment by pixelastic** [comment]
Hey @sabgaby, did you had a chance to test the latest version of the plugin? (`bundle update jekyll-algolia` should do it).

**Comment by pixelastic** [comment]
I'm going to close this issue for now as I didn't get more feedback and the issue seems resolved on my side. Feel free to comment again if you're having other road blocks.
